name: ninja_demo
description: Ninja Demo
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.8

dependencies:
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: 0.8.6
  path_provider: ^2.0.13
  flex_color_scheme: 6.0.1
  equatable:
  form_validator: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
  hive_generator: 1.1.3
  build_runner:

flutter:
  uses-material-design: true
  generate: true
